import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Footer, Navbar, Providers, SparkleCursor, ThreeDBackground} from "../../Components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ghibli Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Providers>
              <div className="fixed inset-0 -z-50">
                  <ThreeDBackground />
              </div>

              <div className="fixed inset-0 z-0 pointer-events-none overflow-hidden">
                  <SparkleCursor />
              </div>

              <Navbar />
              <main className="flex-grow">
                  {children}
              </main>
              <Footer />
        </Providers>
      </body>
    </html>
  );
}
